language: python

sudo: required

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgsl0-dev

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - python setup.py test
